/**
 * Offline world population grid (NASA SEDAC GPWv4, 2015, UN-adjusted, CC BY 4.0).
 * The data module is generated by scripts/build-population.py, which documents the
 * encoding. Rows are decoded lazily and cached, so a query only touches the rows
 * under its circle.
 */
import { COARSE, FINE, GRID_TOTAL_2015, LOG_MIN } from '../data/populationGrid';

const EARTH_RADIUS_M = 6.371e6;
const DEG = Math.PI / 180;
/** Above this radius the 1° grid is plenty and far cheaper than the 0.1° one. */
const COARSE_ABOVE_M = 300_000;
/** Boundary cells are split into SUB × SUB sample points. */
const SUB = 8;

interface GridSpec {
  width: number;
  height: number;
  cellDeg: number;
  logMax: number;
  data: string;
}

class Grid {
  private bytes: Uint8Array | null = null;
  private rowStart: Int32Array | null = null;
  private rows = new Map<number, Float32Array>();
  private spec: GridSpec;

  constructor(spec: GridSpec) {
    this.spec = spec;
  }

  get width() {
    return this.spec.width;
  }
  get height() {
    return this.spec.height;
  }
  get cellDeg() {
    return this.spec.cellDeg;
  }

  private load() {
    if (this.bytes) return;
    const bin = atob(this.spec.data);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    // One pass to find where each row starts.
    const rowStart = new Int32Array(this.spec.height + 1);
    let p = 0;
    for (let y = 0; y < this.spec.height; y++) {
      rowStart[y] = p;
      let x = 0;
      while (x < this.spec.width) {
        if (bytes[p++] === 0) {
          let run = 0;
          let shift = 0;
          let b: number;
          do {
            b = bytes[p++];
            run |= (b & 0x7f) << shift;
            shift += 7;
          } while (b & 0x80);
          x += run;
        } else {
          x += 1;
        }
      }
    }
    rowStart[this.spec.height] = p;
    this.bytes = bytes;
    this.rowStart = rowStart;
  }

  /** People in each cell of row y (row 0 = southernmost). */
  row(y: number): Float32Array {
    const cached = this.rows.get(y);
    if (cached) return cached;
    this.load();
    const bytes = this.bytes!;
    const out = new Float32Array(this.spec.width);
    const span = this.spec.logMax - LOG_MIN;
    let p = this.rowStart![y];
    let x = 0;
    while (x < this.spec.width) {
      const b = bytes[p++];
      if (b === 0) {
        let run = 0;
        let shift = 0;
        let c: number;
        do {
          c = bytes[p++];
          run |= (c & 0x7f) << shift;
          shift += 7;
        } while (c & 0x80);
        x += run;
      } else {
        out[x++] = 10 ** (LOG_MIN + ((b - 1) / 254) * span);
      }
    }
    this.rows.set(y, out);
    return out;
  }
}

const fine = new Grid(FINE);
const coarse = new Grid(COARSE);

/** Great-circle angle between two points, radians. */
function angleBetween(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const s1 = Math.sin(((lat2 - lat1) * DEG) / 2);
  const s2 = Math.sin(((lon2 - lon1) * DEG) / 2);
  const a = s1 * s1 + Math.cos(lat1 * DEG) * Math.cos(lat2 * DEG) * s2 * s2;
  return 2 * Math.asin(Math.min(1, Math.sqrt(a)));
}

/**
 * People living within `radiusM` of a point, in 2015 (multiply by
 * populationScale() for today). Cells wholly inside count fully; cells on the
 * edge are sampled; circles smaller than a cell use that cell's density.
 */
export function peopleWithin2015(latitude: number, longitude: number, radiusM: number): number {
  if (!(radiusM > 0)) return 0;
  const delta = radiusM / EARTH_RADIUS_M;
  if (delta >= Math.PI) return GRID_TOTAL_2015;

  const grid = radiusM > COARSE_ABOVE_M ? coarse : fine;
  const cd = grid.cellDeg;
  const cellAngle = cd * DEG;

  const yOf = (lat: number) => Math.floor((lat + 90) / cd);
  const xOf = (lon: number) => (((Math.floor((lon + 180) / cd) % grid.width) + grid.width) % grid.width);

  // Circle much smaller than a cell: assume the cell's density is uniform.
  const cellHeightM = cellAngle * EARTH_RADIUS_M;
  if (radiusM < cellHeightM * 0.75) {
    const y = Math.min(grid.height - 1, Math.max(0, yOf(latitude)));
    const cellLat = -90 + (y + 0.5) * cd;
    const cellArea = cellHeightM * cellHeightM * Math.max(Math.cos(cellLat * DEG), 1e-3);
    const circleArea = 2 * Math.PI * EARTH_RADIUS_M ** 2 * (1 - Math.cos(delta));
    return (grid.row(y)[xOf(longitude)] * circleArea) / cellArea;
  }

  const latMin = latitude - delta / DEG;
  const latMax = latitude + delta / DEG;
  const yMin = Math.max(0, yOf(latMin));
  const yMax = Math.min(grid.height - 1, yOf(latMax));
  const polar = latMin <= -90 || latMax >= 90;

  let total = 0;
  for (let y = yMin; y <= yMax; y++) {
    const cellLat = -90 + (y + 0.5) * cd;
    const cos = Math.cos(cellLat * DEG);
    // Longitude half-width of the circle at this latitude (generous), in cells.
    let xSpan = grid.width;
    if (!polar && cos > 1e-6) {
      const s = Math.sin(delta) / Math.max(cos, 1e-6);
      const half = s >= 1 ? 180 : Math.asin(s) / DEG + cd;
      xSpan = Math.min(grid.width, Math.ceil((2 * half) / cd) + 2);
    }
    const row = grid.row(y);
    const x0 = xOf(longitude) - Math.floor(xSpan / 2);
    // Half-diagonal of the cell as an angle: cells fully inside/outside skip sampling.
    const halfDiag = (cellAngle / 2) * Math.sqrt(1 + cos * cos);
    for (let i = 0; i < xSpan; i++) {
      const x = (((x0 + i) % grid.width) + grid.width) % grid.width;
      const pop = row[x];
      if (pop === 0) continue;
      const cellLon = -180 + (x + 0.5) * cd;
      const d = angleBetween(latitude, longitude, cellLat, cellLon);
      if (d + halfDiag <= delta) {
        total += pop;
      } else if (d - halfDiag < delta) {
        let inside = 0;
        for (let a = 0; a < SUB; a++) {
          for (let b = 0; b < SUB; b++) {
            const la = cellLat + ((a + 0.5) / SUB - 0.5) * cd;
            const lo = cellLon + ((b + 0.5) / SUB - 0.5) * cd;
            if (angleBetween(latitude, longitude, la, lo) <= delta) inside++;
          }
        }
        total += (pop * inside) / (SUB * SUB);
      }
    }
  }
  return total;
}

export { GRID_TOTAL_2015 };
