#!/usr/bin/env python3
"""
Builds src/data/populationGrid.ts, the offline world population grid.

Source: NASA SEDAC, Gridded Population of the World v4 (GPWv4), population count
adjusted to 2015 UN WPP country totals (CC BY 4.0), as reduced to 0.1° cells by
https://github.com/openaddresses/population (data/gpwv4-2015.csv.gz).

    python3 scripts/build-population.py path/to/gpwv4-2015.csv.gz

Encoding (decoded by src/population/grid.ts):
  * Grids are row-major, row 0 = southernmost (-90°), column 0 = -180°.
  * Each cell's population is stored as one byte: 0 = nobody (< 0.1 people),
    otherwise 10 ** (LOG_MIN + (b - 1) / 254 * (LOG_MAX - LOG_MIN)).
    Log steps are ~6%, and errors cancel: the world total is off by < 0.1%.
  * Runs of zero bytes are written as 0 followed by the run length as an
    unsigned LEB128 varint. Runs never cross rows, so single rows decode alone.
  * The byte stream is base64 so it ships inside the JS bundle.
"""
import base64
import csv
import gzip
import math
import sys

import numpy as np

LOG_MIN = -1.0


def encode(grid):
    log_max = math.log10(grid.max()) + 0.01
    q = np.zeros(grid.shape, dtype=np.uint8)
    nz = grid >= 0.1
    q[nz] = np.clip(1 + np.round((np.log10(grid[nz]) - LOG_MIN) / (log_max - LOG_MIN) * 254), 1, 255)
    out = bytearray()
    for row in q:
        i, n = 0, len(row)
        while i < n:
            if row[i] == 0:
                j = i
                while j < n and row[j] == 0:
                    j += 1
                run = j - i
                out.append(0)
                while True:
                    b = run & 0x7F
                    run >>= 7
                    if run:
                        out.append(b | 0x80)
                    else:
                        out.append(b)
                        break
                i = j
            else:
                out.append(int(row[i]))
                i += 1
    return base64.b64encode(bytes(out)).decode(), log_max


def main(src):
    W, H = 3600, 1800
    fine = np.zeros((H, W))
    with gzip.open(src, "rt") as f:
        rows = csv.reader(f)
        next(rows)
        for r in rows:
            # The file also has 1° rows that re-total the 0.1° rows; skip them.
            if float(r[4]) != 0.1:
                continue
            x = int(round((float(r[2]) + 180) * 10))
            y = int(round((float(r[3]) + 90) * 10))
            fine[y, x] += float(r[6] or 0)
    coarse = fine.reshape(180, 10, 360, 10).sum(axis=(1, 3))

    f_b64, f_max = encode(fine)
    c_b64, c_max = encode(coarse)
    total = fine.sum()

    with open("src/data/populationGrid.ts", "w") as out:
        out.write("/* eslint-disable */\n")
        out.write("// GENERATED by scripts/build-population.py — do not edit.\n")
        out.write("// NASA SEDAC GPWv4 (2015, UN-adjusted), CC BY 4.0. Encoding documented in the script.\n\n")
        out.write(f"export const GRID_TOTAL_2015 = {total:.0f};\n")
        out.write(f"export const LOG_MIN = {LOG_MIN};\n\n")
        out.write(f"/** 0.1° cells, 3600 × 1800. */\nexport const FINE = {{ width: 3600, height: 1800, cellDeg: 0.1, logMax: {f_max!r}, data: '{f_b64}' }};\n\n")
        out.write(f"/** 1° cells, 360 × 180. */\nexport const COARSE = {{ width: 360, height: 180, cellDeg: 1, logMax: {c_max!r}, data: '{c_b64}' }};\n")
    print(f"world 2015: {total/1e9:.3f} B; fine {len(f_b64)/1e6:.2f} MB, coarse {len(c_b64)/1e3:.0f} kB")


if __name__ == "__main__":
    main(sys.argv[1])
